version: 0.0
os: windows
files:
  - source: .
    destination: C:\inetpub\wwwroot
hooks:
  #BeforeInstall:
  #  - location: .\scripts\before-install.bat
  #    timeout: 900
  AfterInstall:
    - location: .\cinfiguration\before-install.bat     
      timeout: 900
 # ApplicationStart:
   # - location: .\scripts\application-start.bat  
  #    timeout: 900
  #ValidateService:
  #  - location: .\scripts\validate-service.bat    
  #    timeout: 900
