--- 
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
phases: 
  build: 
    commands: 
      - "nuget restore"
      - "msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Debug /p:DeployIisAppPath=\"Default Web Site\" /p:PackageAsSingleFile=false /p:OutDir=C:\\inetpub\\wwwroot\\"
  steps:
    - task: CopyFiles@2
      displayName: 'Copy scripts'
      inputs:
        contents: 'C:\\inetpub\\wwwroot\\obj\\Debug\\TEST_AWS.dll'
        targetFolder: 'C:\\inetpub\\wwwroot\\bin\\'

artifacts: 
  files: 
    - TEST_AWS/**/*
    - TEST_AWS/bin/*
    #- TEST_AWS/fonts/**/*
    #- TEST_AWS/Scripts/**/*
    #- TEST_AWS/*.aspx
    #- TEST_AWS/*.master
    #- TEST_AWS/*.xml
    #- TEST_AWS/*.ascx
    #- TEST_AWS/*.ico
    #- appspec.yml
version: 0.2
