--- 
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
    OutDir: C:\\inetpub\\wwwroot\\
phases: 
     
  build: 
    commands: 
      - "nuget restore"
      - "msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK"
      
artifacts: 
  files: 
    files:
    - ./TEST_AWS/bin/Debug/*
    #- TEST_AWS/**/*
    #- TEST_AWS/bin/*
    #- TEST_AWS/fonts/**/*
    #- TEST_AWS/Scripts/**/*
    #- TEST_AWS/*.aspx
    #- TEST_AWS/*.master
    #- TEST_AWS/*.xml
    #- TEST_AWS/*.ascx
    #- TEST_AWS/*.ico
    #- appspec.yml
version: 0.2
