--- 
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
    OutDir: C:\\inetpub\\wwwroot\\
phases: 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - attrib -r $(env.OutDir)*..\* /s
    finally:
      - echo This always runs even if the login command fails
      
  build: 
    commands: 
      - "nuget restore"
      - "msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath=\"Default Web Site\" /p:PackageAsSingleFile=false /p:OutDir=$env:OutDir"
      
artifacts: 
  files: 
    - TEST_AWS/**/*
    #- TEST_AWS/bin/*
    #- TEST_AWS/fonts/**/*
    #- TEST_AWS/Scripts/**/*
    #- TEST_AWS/*.aspx
    #- TEST_AWS/*.master
    #- TEST_AWS/*.xml
    #- TEST_AWS/*.ascx
    #- TEST_AWS/*.ico
    #- appspec.yml
version: 0.2
