--- 
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
    OutDir: C:\\inetpub\\wwwroot\\
phases: 

  pre_build:
    commands:
      - "echo Jenkins echoing env_type"
      - "echo %ENV_TYPE%"
      
  build: 
    commands: 
      - "nuget restore"
      - msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\
artifacts:
  files:
    - TEST_AWS/**/*
version: 0.2
