--- 
artifacts: 
  base-directory: "C:\\inetpub\\wwwroot\\"
  files: 
    - TEST_AWS/**/*
    - scripts/**/*
    - appspec.yml
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
phases: 
  build: 
    commands: 
      - "nuget restore"
      - "msbuild $env:PROJECT.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath=\"Default Web Site\" /p:PackageAsSingleFile=false /p:OutDir=C:\\inetpub\\wwwroot\\"
version: 0.2
