--- 
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.1"
    PROJECT: TEST_AWS
    OutDir: C:\\inetpub\\wwwroot\\
phases: 
     
  build: 
    commands: 
      - "nuget restore"
      - "msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK"
      
artifacts: 
  files: 
    - ./TEST_AWS/bin/Debug/*
    #- TEST_AWS/**/*
version: 0.2
